# Generated by Django 3.0.4 on 2020-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200330_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mastered_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='new_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviewed_list',
            field=models.TextField(default='[]'),
        ),
    ]
