# Generated by Django 3.0.4 on 2020-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed_list',
            field=models.TextField(default=''),
        ),
    ]
