# Generated by Django 3.0.4 on 2020-03-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20200327_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
