# Generated by Django 3.0.4 on 2020-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='level',
            field=models.IntegerField(),
        ),
    ]
